=== AB011W1/HelloMoney/bmg-core-channel-controller-resolver/target/classes/controller-resolver.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:Q1="http://www.component.custom.com/bmb/controllerresolver"
	targetNamespace="http://www.component.custom.com/bmb/controllerresolver"
	elementFormDefault="qualified">
	<xsd:element name="request-to-controller-mapper">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element maxOccurs="unbounded" ref="Q1:resolver" />
			</xsd:sequence>
			<xsd:attribute name="id" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="controller">
		<xsd:complexType>
			<xsd:attribute name="op-code" type="xsd:string" />
			<xsd:attribute name="svc-ver" type="xsd:string" />
			<xsd:attribute name="ref" type="xsd:string" />
			<xsd:attribute name="default" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="resolver">
		<xsd:complexType>
			<xsd:attribute name="resolver-ref" type="xsd:string" />
			<xsd:attribute name="business-id" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="beans">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="Q1:request-to-controller-mapper" />
				<xsd:element ref="Q1:controller-ref-resolver" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="controller-ref-resolver">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element minOccurs="0"  maxOccurs="unbounded" ref="Q1:controller" />
			</xsd:sequence>
			<xsd:attribute name="id" type="xsd:string" />
			<xsd:attribute name="extends" type="xsd:string" use="optional" />
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== AB011W1/HelloMoney/bmg-core-channel-controller-resolver/src/main/resources/promoffer-controller-resolver.xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cr="http://www.component.custom.com/bmb/controllerresolver"
	xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-2.0.xsd
	http://www.component.custom.com/bmb/controllerresolver http://www.component.custom.com/bmb/controllerresolver/controller-resolver.xsd">



	<cr:request-to-controller-mapper id="requestMapper">
	<cr:resolver business-id="AEBRB" resolver-ref="AEBRBPromotOfferResolver" />
	</cr:request-to-controller-mapper>

	<cr:controller-ref-resolver id="AEBRBPromotOfferResolver">
		<!-- Dining offer -->
		<cr:controller op-code="OP1000" svc-ver="1.0" ref="diningOffersControllerVer1" default="true" />
		<cr:controller op-code="OP1000" svc-ver="2.0" ref="diningOffersController" default="false" />
		<cr:controller op-code="OP1000" ref="diningOffersControllerVer1" />

		<cr:controller op-code="OP1001" svc-ver="1.0" ref="diningOfferDetailsControllerVer1" default="true" />
		<cr:controller op-code="OP1001" svc-ver="2.0" ref="diningOfferDetailsController" default="false" />
		<cr:controller op-code="OP1001" ref="diningOfferDetailsControllerVer1" />

		<cr:controller op-code="OP1002" svc-ver="1.0" ref="searchDiningOffersControllerVer1" default="true" />
		<cr:controller op-code="OP1002" svc-ver="2.0" ref="searchDiningOffersController" default="false" />
		<cr:controller op-code="OP1002" ref="searchDiningOffersControllerVer1" />

		<cr:controller op-code="OP1003" svc-ver="1.0" ref="diningSearchDataControllerVer1" default="true" />
		<cr:controller op-code="OP1003" svc-ver="2.0" ref="diningSearchDataController" default="false" />
		<cr:controller op-code="OP1003" ref="diningSearchDataControllerVer1" />

		<!-- EIP Offer -->
		<cr:controller op-code="OP1010" svc-ver="1.0"	ref="eipOffersControllerVer1" default="true" />
		<cr:controller op-code="OP1010" svc-ver="2.0"	ref="eipOffersController" default="false" />
		<cr:controller op-code="OP1010" ref="eipOffersControllerVer1" />

		<cr:controller op-code="OP1011" svc-ver="1.0"	ref="eipOffersDetailControllerVer1" default="true" />
		<cr:controller op-code="OP1011" svc-ver="2.0"	ref="eipOffersDetailController" default="false" />
		<cr:controller op-code="OP1011" ref="eipOffersDetailControllerVer1" />

		<cr:controller op-code="OP1012" svc-ver="1.0"	ref="searchEIPOffersControllerVer1" default="true" />
		<cr:controller op-code="OP1012" svc-ver="2.0"	ref="searchEIPOffersController" default="false" />
		<cr:controller op-code="OP1012" ref="searchEIPOffersControllerVer1" />

		<!-- terms and condition -->
		<cr:controller op-code="OP1020" svc-ver="1.0"	ref="promoOfferTermsAndCondControllerVer1" default="true" />
		<cr:controller op-code="OP1020" svc-ver="2.0"	ref="promoOfferTermsAndCondController" default="false" />
		<cr:controller op-code="OP1020" ref="promoOfferTermsAndCondControllerVer1" />

	</cr:controller-ref-resolver>

</beans>
